sonar.projectKey=harryhub_acquisitions-api
sonar.organization=harryhub
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,dist/**,coverage/**